name: Run Python Script

on:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python Script
        run: |
          pip install requests
          python application.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Set the environment variable here
